apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: kms-frontend-build-listener
spec:
  serviceAccountName: sa-pipeline-trigger
  triggers:
    - name: kms-frontend-build-trigger
      interceptors:
        - name: "CEL filter: only master brancher pushed"
          ref:
            name: "cel"
          params:
          - name: "filter"
            value: "body.ref in ['refs/heads/main']"
      bindings:
        - ref: kms-frontend-build-binding
      template:
        ref: kms-frontend-build-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: kms-frontend-build-binding
spec:
  params:
    - name: git-revision
      value: $(body.after)
    - name: git-repository-url
      value: $(body.repository.clone_url)
    - name: git-repo-name
      value: $(body.repository.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: kms-frontend-build-template
spec:
  params:
    - name: git-revision
      description: The git revision
    - name: git-repository-url
      description: The git repository url
    - name: git-repo-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: kms-frontend-build-trigger-run-
        labels:
          stage: dev
          app: kms-frontend
      spec:
        serviceAccountName: sa-pipeline-runner
        pipelineRef:
          name: buildah
        params:
          - name: build-stage
            value: dev
          - name: git-repo-name
            value: $(tt.params.git-repo-name)
          - name: git-branch
            value: $(tt.params.git-revision)
          - name: insecure-registry
            value: "true"
          - name: git-url
            value: "http://gitea-http.gitea:3000/argo"
          - name: image-url
            value: "harbor.local/library"
          - name: argo-app-name
            value: dev-kms-frontend
          - name: gitops-repo-name
            value: $(tt.params.git-repo-name)-deploy
          - name: gitops-branch
            value: "main"
        workspaces:
        - name: source
          persistentVolumeClaim:
            claimName: pvc-build
        - name: gitops
          emptyDir: {}
