# loki-values.yaml
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
    ring:
      kvstore:
        store: inmemory
  
  # Setting up schemaConfig for better performance
  schemaConfig:
    configs:
      - from: "2023-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  
  # Storage configuration
  storage:
    type: filesystem
  
  # Enable resources limits and requests
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  
  # Pattern ingester for better performance
  pattern_ingester:
    enabled: true
  
  # Configure limits for stability
  limits_config:
    ingestion_rate_mb: 8
    ingestion_burst_size_mb: 16
    max_global_streams_per_user: 5000
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    retention_period: 168h # 7 days retention
    allow_structured_metadata: true
    volume_enabled: true
  
  # Persistence configuration
  persistence:
    enabled: true
    size: 10Gi

# Explicitly set the deployment mode
deploymentMode: SingleBinary
# Configure single binary mode
singleBinary:
  replicas: 1
# Explicitly set other deployment modes to zero replicas
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
# Service configuration
service:
  type: NodePort
  port: 3100
  nodePort: 31000  # Changed to 31000 as requested
# Disable other components since we're using fluent-bit
promtail:
  enabled: true
grafana:
  enabled: false
prometheus:
  enabled: false
# Liveness and readiness probes
readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 30
  timeoutSeconds: 1
  
livenessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 45
  timeoutSeconds: 1
# Security context for better security
securityContext:
  fsGroup: 10001
  runAsUser: 10001
  runAsGroup: 10001
canary:
  enabled: false
gateway:
  enabled: false
results_cache:
  enabled: false
chunks_cache:
  enabled: false
memcached:
  enabled: false
memberlist:
  service:
    enabled: false
